# Generated by Django 5.0.1 on 2025-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=11, max_length=100, unique=True, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
    ]
