# Generated by Django 5.0.1 on 2025-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="manual_status_override",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the status will not be automatically updated based on time.",
                verbose_name="Manual Status Override",
            ),
        ),
    ]
